# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
plex-api-spec.yaml:
  no-ambiguous-paths:
    - '#/paths/~1library~1metadata~1augmentations~1{augmentationId}'
  operation-4xx-response:
    - '#/paths/~1/get/responses'
    - '#/paths/~1:~1eventsource~1notifications/get/responses'
    - '#/paths/~1:~1prefs/get/responses'
    - '#/paths/~1:~1websocket~1notifications/get/responses'
    - '#/paths/~1activities/get/responses'
    - '#/paths/~1butler/get/responses'
    - '#/paths/~1butler/post/responses'
    - '#/paths/~1butler/delete/responses'
    - '#/paths/~1downloadQueue/post/responses'
    - '#/paths/~1hubs/get/responses'
    - '#/paths/~1hubs~1continueWatching/get/responses'
    - '#/paths/~1hubs~1promoted/get/responses'
    - '#/paths/~1identity/get/responses'
    - '#/paths/~1library~1all/get/responses'
    - '#/paths/~1library~1caches/delete/responses'
    - '#/paths/~1library~1clean~1bundles/put/responses'
    - '#/paths/~1library~1file/post/responses'
    - '#/paths/~1library~1matches/get/responses'
    - '#/paths/~1library~1optimize/put/responses'
    - '#/paths/~1library~1randomArtwork/get/responses'
    - '#/paths/~1library~1sections~1all/get/responses'
    - '#/paths/~1library~1sections~1all~1refresh/delete/responses'
    - '#/paths/~1library~1sections~1refresh/post/responses'
    - '#/paths/~1library~1tags/get/responses'
    - '#/paths/~1livetv~1dvrs/get/responses'
    - '#/paths/~1livetv~1dvrs/post/responses'
    - '#/paths/~1livetv~1epg~1countries/get/responses'
    - '#/paths/~1livetv~1epg~1languages/get/responses'
    - '#/paths/~1livetv~1sessions/get/responses'
    - '#/paths/~1log/put/responses'
    - '#/paths/~1media~1grabbers/get/responses'
    - '#/paths/~1media~1grabbers~1devices/get/responses'
    - '#/paths/~1media~1grabbers~1devices~1discover/post/responses'
    - '#/paths/~1media~1providers/get/responses'
    - '#/paths/~1media~1providers~1refresh/post/responses'
    - '#/paths/~1playlists/get/responses'
    - '#/paths/~1status~1sessions/get/responses'
    - '#/paths/~1status~1sessions~1background/get/responses'
    - '#/paths/~1status~1sessions~1history~1all/get/responses'
    - '#/paths/~1updater~1check/put/responses'
    - '#/paths/~1updater~1status/get/responses'
    - '#/paths/~1{transcodeType}~1:~1transcode~1universal~1decision/get/responses'
    - '#/paths/~1downloadQueue~1{queueId}/get/responses'
    - '#/paths/~1downloadQueue~1{queueId}~1add/post/responses'
    - '#/paths/~1downloadQueue~1{queueId}~1items/get/responses'
    - '#/paths/~1library~1metadata~1{ids}/get/responses'
    - '#/paths/~1library~1metadata~1{ids}~1addetect/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1allLeaves/get/responses'
    - '#/paths/~1library~1metadata~1{ids}~1analyze/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1chapterThumbs/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1credits/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1extras/get/responses'
    - '#/paths/~1library~1metadata~1{ids}~1file/get/responses'
    - '#/paths/~1library~1metadata~1{ids}~1index/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1intro/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1match/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1matches/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1merge/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1nearest/get/responses'
    - '#/paths/~1library~1metadata~1{ids}~1prefs/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1refresh/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1related/get/responses'
    - '#/paths/~1library~1metadata~1{ids}~1similar/get/responses'
    - '#/paths/~1library~1metadata~1{ids}~1split/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1subtitles/get/responses'
    - '#/paths/~1library~1metadata~1{ids}~1tree/get/responses'
    - '#/paths/~1library~1metadata~1{ids}~1unmatch/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1users~1top/get/responses'
    - '#/paths/~1library~1metadata~1{ids}~1voiceActivity/put/responses'
    - '#/paths/~1library~1sections~1{sectionId}/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}/delete/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1albums/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1all/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1allLeaves/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1analyze/put/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1arts/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1categories/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1cluster/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1collections/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1computePath/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1emptyTrash/put/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1filters/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1firstCharacters/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1indexes/delete/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1intros/delete/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1location/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1moment/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1nearest/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1prefs/get/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1prefs/put/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1refresh/post/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1refresh/delete/responses'
    - '#/paths/~1library~1sections~1{sectionId}~1sorts/get/responses'
    - '#/paths/~1livetv~1dvrs~1{dvrId}/get/responses'
    - '#/paths/~1livetv~1dvrs~1{dvrId}/delete/responses'
    - '#/paths/~1livetv~1dvrs~1{dvrId}~1lineups/put/responses'
    - '#/paths/~1livetv~1dvrs~1{dvrId}~1lineups/delete/responses'
    - '#/paths/~1livetv~1dvrs~1{dvrId}~1prefs/put/responses'
    - '#/paths/~1livetv~1dvrs~1{dvrId}~1reloadGuide/post/responses'
    - '#/paths/~1livetv~1dvrs~1{dvrId}~1reloadGuide/delete/responses'
    - '#/paths/~1livetv~1sessions~1{sessionId}/get/responses'
    - '#/paths/~1media~1grabbers~1devices~1{deviceId}~1channelmap/put/responses'
    - '#/paths/~1media~1grabbers~1devices~1{deviceId}~1prefs/put/responses'
    - '#/paths/~1media~1grabbers~1devices~1{deviceId}~1scan/post/responses'
    - '#/paths/~1media~1grabbers~1devices~1{deviceId}~1scan/delete/responses'
    - '#/paths/~1playQueues~1{playQueueId}~1items/delete/responses'
    - '#/paths/~1downloadQueue~1{queueId}~1item~1{itemId}~1media/get/responses'
    - '#/paths/~1downloadQueue~1{queueId}~1items~1{itemId}/get/responses'
    - '#/paths/~1downloadQueue~1{queueId}~1items~1{itemId}/delete/responses'
    - >-
      #/paths/~1downloadQueue~1{queueId}~1items~1{itemId}~1restart/post/responses
    - '#/paths/~1library~1metadata~1{ids}~1{element}/put/responses'
    - '#/paths/~1library~1metadata~1{ids}~1{element}/post/responses'
    - >-
      #/paths/~1library~1sections~1{sectionId}~1composite~1{updatedAt}/get/responses
    - '#/paths/~1livetv~1dvrs~1{dvrId}~1channels~1{channel}~1tune/post/responses'
    - '#/paths/~1livetv~1dvrs~1{dvrId}~1devices~1{deviceId}/put/responses'
    - '#/paths/~1livetv~1dvrs~1{dvrId}~1devices~1{deviceId}/delete/responses'
    - '#/paths/~1library~1metadata~1{ids}~1{element}~1{timestamp}/get/responses'
